IF NOT EXISTS (SELECT * FROM sys.views WHERE object_id = OBJECT_ID(N'[dbo].[v_Logger]'))
EXEC dbo.sp_executesql @statement = N'CREATE VIEW [dbo].[v_Logger]
as
SELECT  [LogID]
      ,[LogDate]
      ,[StoreID]
      ,[WorkStationID]
      ,[GarmentStoreID]
      ,[LaborID]
      ,[LaborCode]
      ,[LaborName]
      ,[ProcessID]
      ,[ProcessName]
      ,[CustomerID]
      ,[CustomerName]
      ,[DepartmentID]
      ,[DepartmentName]
      ,[DetailGuid]
      ,[GarmentID]
      ,[GarmentName]
      ,[ArticleCode]
      ,[InvoiceLine]
      ,[MarkInDate]
      ,[MarkInEmpID]
      ,[EmployeeID]
      ,[Amount]
      ,[CommCost]
      ,[LaborCost]
      ,[TimeCost]
      ,[PieceCost]
      ,[State]
      ,[TimeMode]
      ,[CostMode]
      ,[TimeStampIn]
      ,[TimeStampOut]
      ,[Starch]
      ,[Package]
      ,[Comment]
      ,[FlagTag]
      ,[Reason]
      ,[Notes]
  FROM [PPOHDB].[dbo].[Logger]'